=== GlebYudenok/EpamTasks/Task3/src/main/resources/Candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="candies" type="candiesType"/>
  <xs:complexType name="candyTypeType">
    <xs:all>
      <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="CARAMEL"/>
            <xs:enumeration value="CHOCOLATE"/>
            <xs:enumeration value= "SUGAR"/>
            <xs:enumeration value="CHEWING"/>
            <xs:enumeration value="MARMALADE"/>
            <xs:enumeration value="MARSHMALLOW"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="filling">
        <xs:simpleType>
        <xs:restriction base="xs:boolean">
          <xs:enumeration value="true"/>
          <xs:enumeration value="false"/>
        </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="ingredientType">
    <xs:sequence>
      <xs:element name="quantity">
        <xs:simpleType>
          <xs:restriction base="xs:integer">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="unit" use="required"/>
  </xs:complexType>
  <xs:complexType name="ingredientsType">
    <xs:sequence>
      <xs:element type="ingredientType" name="ingredient" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="valueType">
    <xs:sequence>
      <xs:element type="xs:double" name="fat"/>
      <xs:element type="xs:double" name="protein"/>
      <xs:element type="xs:double" name="carbohydrates"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="unit" use="required"/>
  </xs:complexType>
  <xs:complexType name="producerType">
    <xs:sequence>
      <xs:element type="xs:string" name="enterprise"/>
      <xs:element type="xs:date" name="foundingDate"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="country" use="optional"/>
  </xs:complexType>
  <xs:complexType name="candyType">
    <xs:sequence>
      <xs:element type="xs:string" name="title"/>
      <xs:element type="xs:string" name="energy"/>
      <xs:element type="candyTypeType" name="candyType"/>
      <xs:element type="ingredientsType" name="ingredients"/>
      <xs:element type="valueType" name="value"/>
      <xs:element type="producerType" name="producer"/>
    </xs:sequence>
    <xs:attribute type="xs:ID" name="id" use="required"/>
  </xs:complexType>
  <xs:complexType name="candiesType">
    <xs:sequence>
      <xs:element type="candyType" name="candy" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== GlebYudenok/EpamTasks/Task3/src/test/resources/WrongCandies.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<candies  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Candies.xsd">
    <candy id="3">
        <name>Sweet</name>
        <energy>24</energy>
        <candyType>
            <type>CHEWING</type>
            <filling>false</filling>
        </candyType>
       ="pizda">
                <quantity>10</quantity>
                <name>xyi</name>
            </ingredient>
        </ingredients>
        <value unit="mg">
            <fat>20</fat>
            <protein>50</protein>
            <carbohydrates>23</carbohydrates>
        </value>
        <producer country="Blr">
            <enterprise>entprs</enterprise>
        </producer>
    </candy>

    <candy id="2">
        <name>Sweet</name>
        <energy>24</energy>
        <candyType>
            <type>CHOCOLATE</type>
            <filling>true</filling>
        </candyType>
        <ingredients>
        <value unit="mg">
            <fat>20</fat>
            <protein>50</protein>
            <carbohydrates>23</carbohydrates>
        </value>
        <producer country="Blr">
            <enterprise>entprs</enterprise>
        </producer>
    </candy>
</candies>

=== GlebYudenok/EpamTasks/Task3/src/main/resources/Candies.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<candies  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Candies.xsd">
    <candy id="1">
        <title>Lindor</title>
        <energy>630</energy>
        <candyType>
            <type>CHOCOLATE</type>
            <filling>true</filling>
        </candyType>
        <ingredients>
            <ingredient unit="mg">
                <quantity>15</quantity>
                <name>cacao</name>
            </ingredient>
            <ingredient unit="mg">
                <quantity>20</quantity>
                <name>sugar</name>
            </ingredient>
        </ingredients>
        <value unit="mg">
            <fat>53</fat>
            <protein>4.3</protein>
            <carbohydrates>33</carbohydrates>
        </value>
        <producer country="CHE">
            <enterprise>Lindt</enterprise>
        </producer>
    </candy>

    <candy id="2">
        <title>Konafetto</title>
        <energy>540</energy>
        <candyType>
            <type>CARAMEL</type>
            <filling>false</filling>
        </candyType>
        <ingredients>
            <ingredient unit="g">
                <quantity>10</quantity>
                <name>sugar</name>
            </ingredient>
            <ingredient unit="g">
                <quantity>15</quantity>
                <name>cacao</name>
            </ingredient>
        </ingredients>
        <value unit="kg">
            <fat>4.3</fat>
            <protein>33</protein>
            <carbohydrates>53</carbohydrates>
        </value>
        <producer country="UKR">
            <enterprise>Roshan</enterprise>
        </producer>
    </candy>
</candies>

=== GlebYudenok/EpamTasks/Task3/src/test/resources/Candies.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<candies  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Candies.xsd">
    <candy id="1">
        <title>Lindor</title>
        <energy>630</energy>
        <candyType>
            <type>CHOCOLATE</type>
            <filling>false</filling>
        </candyType>
        <ingredients>
            <ingredient unit="mg">
                <quantity>15</quantity>
                <name>cacao</name>
            </ingredient>
            <ingredient unit="mg">
                <quantity>20</quantity>
                <name>sugar</name>
            </ingredient>
            <ingredient unit="ml">
                <quantity>120</quantity>
                <name>milk</name>
            </ingredient>
        </ingredients>
        <value unit="mg">
            <fat>53</fat>
            <protein>4.3</protein>
            <carbohydrates>33</carbohydrates>
        </value>
        <producer country="CHE">
            <enterprise>Lindt</enterprise>
        </producer>
    </candy>
</candies>
